import { TILES, type MapDefinition } from '../../engine'
import { outdoorDay } from './environments'

export const town: MapDefinition = {
  id: 'town',
  name: 'Mossvale Village',
  tiles: [
    'TTTTTTTTT""..""TTTTTTTTT',
    'TTTTTTTTT""..""TTTTTTTTT',
    'TT,,,,,,,,,..,,,,,,,,,TT',
    'TT,,,,,,,,,..,,,,,,,,,TT',
    'TT,,,,,,,,,..,,,,,,,,,TT',
    'TT,,,,,,,,,..,,,,,,,,,TT',
    'TT,,,,,,b,,..,,b,,,,,,TT',
    'TT,,,.,,,,,..,,,,.,,,,TT',
    'TT,,,.............,,,,TT',
    'TT,,,,,,,,,..,,,,,,,,,TT',
    'TT,ffff,,,,..,,,,,,,,,TT',
    'TT,ffff,,,,..,,,,,,,,,TT',
    'TT,,,,,,,,,..,,,,,,,,,TT',
    'TT,======,,..,,,,,,,,,TT',
    'TT,=ffff=,,..,,,,,,,,,TT',
    'TT,=ffff=,,......,,,,,TT',
    'TT,======,,..,,,,,,,,,TT',
    'TT,,,,,,,,,..,,,,,,,,,TT',
    'TTsssssssss..sssssssssTT',
    'TT~~~~~~~~~dd~~~~~~~~~TT',
    'T~~~~~~~~~~dd~~~~~~~~~~T',
    '~~~~~~~~~~~~~~~~~~~~~~~~',
  ],
  palette: {
    T: TILES.tree,
    ',': TILES.grass,
    '.': TILES.path,
    '"': TILES.tallGrass,
    f: TILES.flowers,
    '=': TILES.fence,
    b: TILES.bush,
    s: { ...TILES.sand, side: 'sand' },
    '~': TILES.water,
    d: TILES.dock,
  },
  border: 6,
  objects: [
    { type: 'building', x: 4, y: 4, w: 4, d: 3, props: { roof: '#c9483b', door: 1, windows: [2.5], chimney: true } },
    { type: 'building', x: 16, y: 4, w: 4, d: 3, props: { roof: '#3f6fb5', door: 1, windows: [2.5] } },
    { type: 'building', x: 14, y: 11, w: 6, d: 4, props: { style: 'lab', roof: '#5a7a96', door: 2, windows: [0.5, 4.5] } },
    { type: 'sign', x: 10, y: 11, text: ['MOSSVALE VILLAGE', 'Where every road begins with a single step.'] },
    { type: 'sign', x: 3, y: 7, text: 'Your house. Home, sweet home.' },
    { type: 'mailbox', x: 15, y: 7, text: "The Birch family's mailbox. It's stuffed with seed catalogues." },
    { type: 'sign', x: 13, y: 13, text: ['HAWTHORNE RESEARCH LAB', 'Studying how people and nature share the valley.'] },
    { type: 'lamp', x: 10, y: 9 },
    { type: 'lamp', x: 13, y: 9 },
    { type: 'lamp', x: 10, y: 17 },
    { type: 'lamp', x: 13, y: 17 },
  ],
  npcs: [
    {
      id: 'poppy',
      sprite: 'florist',
      name: 'Poppy',
      x: 4,
      y: 12,
      behavior: { type: 'wander', radius: 2 },
      dialogue: [
        'Every morning I count the flowers in this garden.',
        'Yesterday there were forty-two. Today there are forty-three!',
      ],
    },
    {
      id: 'tomas',
      sprite: 'elder',
      name: 'Old Tomas',
      x: 9,
      y: 11,
      facing: 'right',
      behavior: { type: 'look' },
      dialogue: [
        'When I was your age, this village was three houses and a very stubborn goat.',
        'Now look at it! Four buildings AND a lab.',
      ],
    },
    {
      id: 'pip',
      sprite: 'kid',
      name: 'Pip',
      x: 19,
      y: 9,
      behavior: { type: 'wander', radius: 3 },
      dialogue: "Race you to the pier! …Actually, I'm still tired from the last race.",
    },
    {
      id: 'wade',
      sprite: 'fisher',
      name: 'Wade',
      x: 12,
      y: 20,
      facing: 'down',
      behavior: { type: 'idle' },
      dialogue: ["The fish aren't biting today.", "They weren't biting yesterday either. I just like the view."],
    },
  ],
  warps: [
    { x: 5, y: 7, dir: 'up', to: { map: 'playerHouse1F', x: 5, y: 7, facing: 'up' } },
    { x: 17, y: 7, dir: 'up', to: { map: 'neighbourHouse', x: 5, y: 7, facing: 'up' } },
    { x: 16, y: 15, dir: 'up', to: { map: 'lab', x: 7, y: 11, facing: 'up' } },
  ],
  triggers: [
    {
      x: 9,
      y: 1,
      w: 6,
      script: async (ctx) => {
        await ctx.say([
          'Tall grass rustles on the path ahead…',
          "It's not safe to wander out there alone. Better head back for now.",
        ])
        await ctx.player.walk('down', 1)
      },
    },
  ],
  environment: outdoorDay,
}
